//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTHPlayer.Forms.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ISO639Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ISO639Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PTHPlayer.Forms.Resources.ISO639Resources", typeof(ISO639Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abkhaz.
        /// </summary>
        public static string Abkhaz {
            get {
                return ResourceManager.GetString("Abkhaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afar.
        /// </summary>
        public static string Afar {
            get {
                return ResourceManager.GetString("Afar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afrikaans.
        /// </summary>
        public static string Afrikaans {
            get {
                return ResourceManager.GetString("Afrikaans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akan.
        /// </summary>
        public static string Akan {
            get {
                return ResourceManager.GetString("Akan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albanian.
        /// </summary>
        public static string Albanian {
            get {
                return ResourceManager.GetString("Albanian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amharic.
        /// </summary>
        public static string Amharic {
            get {
                return ResourceManager.GetString("Amharic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aragonese.
        /// </summary>
        public static string Aragonese {
            get {
                return ResourceManager.GetString("Aragonese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armenian.
        /// </summary>
        public static string Armenian {
            get {
                return ResourceManager.GetString("Armenian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assamese.
        /// </summary>
        public static string Assamese {
            get {
                return ResourceManager.GetString("Assamese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avaric.
        /// </summary>
        public static string Avaric {
            get {
                return ResourceManager.GetString("Avaric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avestan.
        /// </summary>
        public static string Avestan {
            get {
                return ResourceManager.GetString("Avestan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aymara.
        /// </summary>
        public static string Aymara {
            get {
                return ResourceManager.GetString("Aymara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaijani.
        /// </summary>
        public static string Azerbaijani {
            get {
                return ResourceManager.GetString("Azerbaijani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bambara.
        /// </summary>
        public static string Bambara {
            get {
                return ResourceManager.GetString("Bambara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bashkir.
        /// </summary>
        public static string Bashkir {
            get {
                return ResourceManager.GetString("Bashkir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basque.
        /// </summary>
        public static string Basque {
            get {
                return ResourceManager.GetString("Basque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belarusian.
        /// </summary>
        public static string Belarusian {
            get {
                return ResourceManager.GetString("Belarusian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bengali.
        /// </summary>
        public static string Bengali {
            get {
                return ResourceManager.GetString("Bengali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bihari.
        /// </summary>
        public static string Bihari {
            get {
                return ResourceManager.GetString("Bihari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bislama.
        /// </summary>
        public static string Bislama {
            get {
                return ResourceManager.GetString("Bislama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosnian.
        /// </summary>
        public static string Bosnian {
            get {
                return ResourceManager.GetString("Bosnian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breton.
        /// </summary>
        public static string Breton {
            get {
                return ResourceManager.GetString("Breton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgarian.
        /// </summary>
        public static string Bulgarian {
            get {
                return ResourceManager.GetString("Bulgarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burmese.
        /// </summary>
        public static string Burmese {
            get {
                return ResourceManager.GetString("Burmese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalan.
        /// </summary>
        public static string Catalan {
            get {
                return ResourceManager.GetString("Catalan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chamorro.
        /// </summary>
        public static string Chamorro {
            get {
                return ResourceManager.GetString("Chamorro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chechen.
        /// </summary>
        public static string Chechen {
            get {
                return ResourceManager.GetString("Chechen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chichewa.
        /// </summary>
        public static string Chichewa {
            get {
                return ResourceManager.GetString("Chichewa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        public static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Church Slavic.
        /// </summary>
        public static string ChurchSlavic {
            get {
                return ResourceManager.GetString("ChurchSlavic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuvash.
        /// </summary>
        public static string Chuvash {
            get {
                return ResourceManager.GetString("Chuvash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cornish.
        /// </summary>
        public static string Cornish {
            get {
                return ResourceManager.GetString("Cornish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corsican.
        /// </summary>
        public static string Corsican {
            get {
                return ResourceManager.GetString("Corsican", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cree.
        /// </summary>
        public static string Cree {
            get {
                return ResourceManager.GetString("Cree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        public static string Croatian {
            get {
                return ResourceManager.GetString("Croatian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech.
        /// </summary>
        public static string Czech {
            get {
                return ResourceManager.GetString("Czech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danish.
        /// </summary>
        public static string Danish {
            get {
                return ResourceManager.GetString("Danish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divehi.
        /// </summary>
        public static string Divehi {
            get {
                return ResourceManager.GetString("Divehi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        public static string Dutch {
            get {
                return ResourceManager.GetString("Dutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dzongkha.
        /// </summary>
        public static string Dzongkha {
            get {
                return ResourceManager.GetString("Dzongkha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esperanto.
        /// </summary>
        public static string Esperanto {
            get {
                return ResourceManager.GetString("Esperanto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estonian.
        /// </summary>
        public static string Estonian {
            get {
                return ResourceManager.GetString("Estonian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ewe.
        /// </summary>
        public static string Ewe {
            get {
                return ResourceManager.GetString("Ewe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faroese.
        /// </summary>
        public static string Faroese {
            get {
                return ResourceManager.GetString("Faroese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fijian.
        /// </summary>
        public static string Fijian {
            get {
                return ResourceManager.GetString("Fijian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finnish.
        /// </summary>
        public static string Finnish {
            get {
                return ResourceManager.GetString("Finnish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fulah.
        /// </summary>
        public static string Fulah {
            get {
                return ResourceManager.GetString("Fulah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaelic.
        /// </summary>
        public static string Gaelic {
            get {
                return ResourceManager.GetString("Gaelic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galician.
        /// </summary>
        public static string Galician {
            get {
                return ResourceManager.GetString("Galician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ganda.
        /// </summary>
        public static string Ganda {
            get {
                return ResourceManager.GetString("Ganda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Georgian.
        /// </summary>
        public static string Georgian {
            get {
                return ResourceManager.GetString("Georgian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek.
        /// </summary>
        public static string Greek {
            get {
                return ResourceManager.GetString("Greek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guarani.
        /// </summary>
        public static string Guarani {
            get {
                return ResourceManager.GetString("Guarani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gujarati.
        /// </summary>
        public static string Gujarati {
            get {
                return ResourceManager.GetString("Gujarati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haitian.
        /// </summary>
        public static string Haitian {
            get {
                return ResourceManager.GetString("Haitian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hausa.
        /// </summary>
        public static string Hausa {
            get {
                return ResourceManager.GetString("Hausa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hebrew.
        /// </summary>
        public static string Hebrew {
            get {
                return ResourceManager.GetString("Hebrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herero.
        /// </summary>
        public static string Herero {
            get {
                return ResourceManager.GetString("Herero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hindi.
        /// </summary>
        public static string Hindi {
            get {
                return ResourceManager.GetString("Hindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HiriMotu.
        /// </summary>
        public static string HiriMotu {
            get {
                return ResourceManager.GetString("HiriMotu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungarian.
        /// </summary>
        public static string Hungarian {
            get {
                return ResourceManager.GetString("Hungarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icelandic.
        /// </summary>
        public static string Icelandic {
            get {
                return ResourceManager.GetString("Icelandic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ido.
        /// </summary>
        public static string Ido {
            get {
                return ResourceManager.GetString("Ido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igbo.
        /// </summary>
        public static string Igbo {
            get {
                return ResourceManager.GetString("Igbo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indonesian.
        /// </summary>
        public static string Indonesian {
            get {
                return ResourceManager.GetString("Indonesian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interlingua.
        /// </summary>
        public static string Interlingua {
            get {
                return ResourceManager.GetString("Interlingua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interlingue.
        /// </summary>
        public static string Interlingue {
            get {
                return ResourceManager.GetString("Interlingue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inuktitut.
        /// </summary>
        public static string Inuktitut {
            get {
                return ResourceManager.GetString("Inuktitut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inupiaq.
        /// </summary>
        public static string Inupiaq {
            get {
                return ResourceManager.GetString("Inupiaq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irish.
        /// </summary>
        public static string Irish {
            get {
                return ResourceManager.GetString("Irish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        public static string Italian {
            get {
                return ResourceManager.GetString("Italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        public static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Javanese.
        /// </summary>
        public static string Javanese {
            get {
                return ResourceManager.GetString("Javanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalaallisut.
        /// </summary>
        public static string Kalaallisut {
            get {
                return ResourceManager.GetString("Kalaallisut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kannada.
        /// </summary>
        public static string Kannada {
            get {
                return ResourceManager.GetString("Kannada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kanuri.
        /// </summary>
        public static string Kanuri {
            get {
                return ResourceManager.GetString("Kanuri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kashmiri.
        /// </summary>
        public static string Kashmiri {
            get {
                return ResourceManager.GetString("Kashmiri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kazakh.
        /// </summary>
        public static string Kazakh {
            get {
                return ResourceManager.GetString("Kazakh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khmer.
        /// </summary>
        public static string Khmer {
            get {
                return ResourceManager.GetString("Khmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kikuyu.
        /// </summary>
        public static string Kikuyu {
            get {
                return ResourceManager.GetString("Kikuyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinyarwanda.
        /// </summary>
        public static string Kinyarwanda {
            get {
                return ResourceManager.GetString("Kinyarwanda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kirghiz.
        /// </summary>
        public static string Kirghiz {
            get {
                return ResourceManager.GetString("Kirghiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kirundi.
        /// </summary>
        public static string Kirundi {
            get {
                return ResourceManager.GetString("Kirundi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komi.
        /// </summary>
        public static string Komi {
            get {
                return ResourceManager.GetString("Komi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kongo.
        /// </summary>
        public static string Kongo {
            get {
                return ResourceManager.GetString("Kongo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean.
        /// </summary>
        public static string Korean {
            get {
                return ResourceManager.GetString("Korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuanyama.
        /// </summary>
        public static string Kuanyama {
            get {
                return ResourceManager.GetString("Kuanyama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurdish.
        /// </summary>
        public static string Kurdish {
            get {
                return ResourceManager.GetString("Kurdish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lao.
        /// </summary>
        public static string Lao {
            get {
                return ResourceManager.GetString("Lao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latin.
        /// </summary>
        public static string Latin {
            get {
                return ResourceManager.GetString("Latin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latvian.
        /// </summary>
        public static string Latvian {
            get {
                return ResourceManager.GetString("Latvian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limburgish.
        /// </summary>
        public static string Limburgish {
            get {
                return ResourceManager.GetString("Limburgish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lingala.
        /// </summary>
        public static string Lingala {
            get {
                return ResourceManager.GetString("Lingala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithuanian.
        /// </summary>
        public static string Lithuanian {
            get {
                return ResourceManager.GetString("Lithuanian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LubaKatanga.
        /// </summary>
        public static string LubaKatanga {
            get {
                return ResourceManager.GetString("LubaKatanga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luxembourgish.
        /// </summary>
        public static string Luxembourgish {
            get {
                return ResourceManager.GetString("Luxembourgish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macedonian.
        /// </summary>
        public static string Macedonian {
            get {
                return ResourceManager.GetString("Macedonian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malagasy.
        /// </summary>
        public static string Malagasy {
            get {
                return ResourceManager.GetString("Malagasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malay.
        /// </summary>
        public static string Malay {
            get {
                return ResourceManager.GetString("Malay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malayalam.
        /// </summary>
        public static string Malayalam {
            get {
                return ResourceManager.GetString("Malayalam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maltese.
        /// </summary>
        public static string Maltese {
            get {
                return ResourceManager.GetString("Maltese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manx.
        /// </summary>
        public static string Manx {
            get {
                return ResourceManager.GetString("Manx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maori.
        /// </summary>
        public static string Maori {
            get {
                return ResourceManager.GetString("Maori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marathi.
        /// </summary>
        public static string Marathi {
            get {
                return ResourceManager.GetString("Marathi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marshallese.
        /// </summary>
        public static string Marshallese {
            get {
                return ResourceManager.GetString("Marshallese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moldavian.
        /// </summary>
        public static string Moldavian {
            get {
                return ResourceManager.GetString("Moldavian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mongolian.
        /// </summary>
        public static string Mongolian {
            get {
                return ResourceManager.GetString("Mongolian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nauru.
        /// </summary>
        public static string Nauru {
            get {
                return ResourceManager.GetString("Nauru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navajo.
        /// </summary>
        public static string Navajo {
            get {
                return ResourceManager.GetString("Navajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ndonga.
        /// </summary>
        public static string Ndonga {
            get {
                return ResourceManager.GetString("Ndonga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepali.
        /// </summary>
        public static string Nepali {
            get {
                return ResourceManager.GetString("Nepali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NorthernSami.
        /// </summary>
        public static string NorthernSami {
            get {
                return ResourceManager.GetString("NorthernSami", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NorthNdebele.
        /// </summary>
        public static string NorthNdebele {
            get {
                return ResourceManager.GetString("NorthNdebele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norwegian.
        /// </summary>
        public static string Norwegian {
            get {
                return ResourceManager.GetString("Norwegian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NorwegianBokmal.
        /// </summary>
        public static string NorwegianBokmal {
            get {
                return ResourceManager.GetString("NorwegianBokmal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NorwegianNynorsk.
        /// </summary>
        public static string NorwegianNynorsk {
            get {
                return ResourceManager.GetString("NorwegianNynorsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occitan.
        /// </summary>
        public static string Occitan {
            get {
                return ResourceManager.GetString("Occitan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ojibwa.
        /// </summary>
        public static string Ojibwa {
            get {
                return ResourceManager.GetString("Ojibwa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oriya.
        /// </summary>
        public static string Oriya {
            get {
                return ResourceManager.GetString("Oriya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oromo.
        /// </summary>
        public static string Oromo {
            get {
                return ResourceManager.GetString("Oromo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ossetian.
        /// </summary>
        public static string Ossetian {
            get {
                return ResourceManager.GetString("Ossetian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pali.
        /// </summary>
        public static string Pali {
            get {
                return ResourceManager.GetString("Pali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panjabi.
        /// </summary>
        public static string Panjabi {
            get {
                return ResourceManager.GetString("Panjabi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pashto.
        /// </summary>
        public static string Pashto {
            get {
                return ResourceManager.GetString("Pashto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persian.
        /// </summary>
        public static string Persian {
            get {
                return ResourceManager.GetString("Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        public static string Polish {
            get {
                return ResourceManager.GetString("Polish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        public static string Portuguese {
            get {
                return ResourceManager.GetString("Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quechua.
        /// </summary>
        public static string Quechua {
            get {
                return ResourceManager.GetString("Quechua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RaetoRomance.
        /// </summary>
        public static string RaetoRomance {
            get {
                return ResourceManager.GetString("RaetoRomance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romanian.
        /// </summary>
        public static string Romanian {
            get {
                return ResourceManager.GetString("Romanian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samoan.
        /// </summary>
        public static string Samoan {
            get {
                return ResourceManager.GetString("Samoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sango.
        /// </summary>
        public static string Sango {
            get {
                return ResourceManager.GetString("Sango", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanskrit.
        /// </summary>
        public static string Sanskrit {
            get {
                return ResourceManager.GetString("Sanskrit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sardinian.
        /// </summary>
        public static string Sardinian {
            get {
                return ResourceManager.GetString("Sardinian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbian.
        /// </summary>
        public static string Serbian {
            get {
                return ResourceManager.GetString("Serbian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shona.
        /// </summary>
        public static string Shona {
            get {
                return ResourceManager.GetString("Shona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SichuanYi.
        /// </summary>
        public static string SichuanYi {
            get {
                return ResourceManager.GetString("SichuanYi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sindhi.
        /// </summary>
        public static string Sindhi {
            get {
                return ResourceManager.GetString("Sindhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinhala.
        /// </summary>
        public static string Sinhala {
            get {
                return ResourceManager.GetString("Sinhala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovak.
        /// </summary>
        public static string Slovak {
            get {
                return ResourceManager.GetString("Slovak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovenian.
        /// </summary>
        public static string Slovenian {
            get {
                return ResourceManager.GetString("Slovenian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somali.
        /// </summary>
        public static string Somali {
            get {
                return ResourceManager.GetString("Somali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SouthernSotho.
        /// </summary>
        public static string SouthernSotho {
            get {
                return ResourceManager.GetString("SouthernSotho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SouthNdebele.
        /// </summary>
        public static string SouthNdebele {
            get {
                return ResourceManager.GetString("SouthNdebele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sundanese.
        /// </summary>
        public static string Sundanese {
            get {
                return ResourceManager.GetString("Sundanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swahili.
        /// </summary>
        public static string Swahili {
            get {
                return ResourceManager.GetString("Swahili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swati.
        /// </summary>
        public static string Swati {
            get {
                return ResourceManager.GetString("Swati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish.
        /// </summary>
        public static string Swedish {
            get {
                return ResourceManager.GetString("Swedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagalog.
        /// </summary>
        public static string Tagalog {
            get {
                return ResourceManager.GetString("Tagalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tahitian.
        /// </summary>
        public static string Tahitian {
            get {
                return ResourceManager.GetString("Tahitian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tajik.
        /// </summary>
        public static string Tajik {
            get {
                return ResourceManager.GetString("Tajik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamil.
        /// </summary>
        public static string Tamil {
            get {
                return ResourceManager.GetString("Tamil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tatar.
        /// </summary>
        public static string Tatar {
            get {
                return ResourceManager.GetString("Tatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telugu.
        /// </summary>
        public static string Telugu {
            get {
                return ResourceManager.GetString("Telugu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thai.
        /// </summary>
        public static string Thai {
            get {
                return ResourceManager.GetString("Thai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tibetan.
        /// </summary>
        public static string Tibetan {
            get {
                return ResourceManager.GetString("Tibetan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tigrinya.
        /// </summary>
        public static string Tigrinya {
            get {
                return ResourceManager.GetString("Tigrinya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tonga.
        /// </summary>
        public static string Tonga {
            get {
                return ResourceManager.GetString("Tonga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tsonga.
        /// </summary>
        public static string Tsonga {
            get {
                return ResourceManager.GetString("Tsonga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tswana.
        /// </summary>
        public static string Tswana {
            get {
                return ResourceManager.GetString("Tswana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        public static string Turkish {
            get {
                return ResourceManager.GetString("Turkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkmen.
        /// </summary>
        public static string Turkmen {
            get {
                return ResourceManager.GetString("Turkmen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twi.
        /// </summary>
        public static string Twi {
            get {
                return ResourceManager.GetString("Twi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uighur.
        /// </summary>
        public static string Uighur {
            get {
                return ResourceManager.GetString("Uighur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian.
        /// </summary>
        public static string Ukrainian {
            get {
                return ResourceManager.GetString("Ukrainian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urdu.
        /// </summary>
        public static string Urdu {
            get {
                return ResourceManager.GetString("Urdu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzbek.
        /// </summary>
        public static string Uzbek {
            get {
                return ResourceManager.GetString("Uzbek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venda.
        /// </summary>
        public static string Venda {
            get {
                return ResourceManager.GetString("Venda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese.
        /// </summary>
        public static string Vietnamese {
            get {
                return ResourceManager.GetString("Vietnamese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volapuk.
        /// </summary>
        public static string Volapuk {
            get {
                return ResourceManager.GetString("Volapuk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walloon.
        /// </summary>
        public static string Walloon {
            get {
                return ResourceManager.GetString("Walloon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welsh.
        /// </summary>
        public static string Welsh {
            get {
                return ResourceManager.GetString("Welsh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WesternFrisian.
        /// </summary>
        public static string WesternFrisian {
            get {
                return ResourceManager.GetString("WesternFrisian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wolof.
        /// </summary>
        public static string Wolof {
            get {
                return ResourceManager.GetString("Wolof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xhosa.
        /// </summary>
        public static string Xhosa {
            get {
                return ResourceManager.GetString("Xhosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yiddish.
        /// </summary>
        public static string Yiddish {
            get {
                return ResourceManager.GetString("Yiddish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yoruba.
        /// </summary>
        public static string Yoruba {
            get {
                return ResourceManager.GetString("Yoruba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zhuang.
        /// </summary>
        public static string Zhuang {
            get {
                return ResourceManager.GetString("Zhuang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zulu.
        /// </summary>
        public static string Zulu {
            get {
                return ResourceManager.GetString("Zulu", resourceCulture);
            }
        }
    }
}
